"""Lazy access to the model workstream, and the artifact it loads from.

Two responsibilities, both about not crashing a process that is missing a
workstream:

* **Import lazily.** ``agrigrade.model`` needs scikit-learn, which is not a
  dependency of the shared spine. Importing it at module scope would make
  ``agrigrade.api`` unimportable without the ``model`` extra, so the import
  happens inside the accessor and a failure becomes
  :class:`~agrigrade.core.errors.WorkstreamNotImplementedError`, which the API
  turns into a 501 rather than a 500.
* **Load once, cache, verify.** A serialized forest is only as safe as the
  context saved beside it, so the bundle is verified against the live schema on
  load and a mismatch is refused rather than warned about.

The model is fitted on synthetic data from
:mod:`agrigrade.model.mock`, because the feature stage's real captures are not
committed. That is stated in ``/api/v1/health`` too: a grade from this server is
a real ensemble decision on real measurements, but the weights have never seen a
photograph.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

from agrigrade.core.errors import ModelNotLoadedError, WorkstreamNotImplementedError

#: Cache filename for the demo artifact. Gitignored, regenerated by
#: ``python -m agrigrade.model.train``.
DEFAULT_ARTIFACT = "grader"


@dataclass(frozen=True, slots=True)
class LoadedModel:
    """A fitted grader plus the manifest describing where it came from."""

    grader: Any
    manifest: dict[str, Any]
    feature_names: tuple[str, ...]
    schema_version: int

    @property
    def n_estimators(self) -> int:
        return int(self.manifest.get("n_estimators", 0))

    @property
    def checksum(self) -> str:
        return str(self.manifest.get("checksum", ""))


_lock = threading.Lock()
_cached: LoadedModel | None = None


def model_module() -> ModuleType:
    """Import ``agrigrade.model`` on demand.

    Raises:
        WorkstreamNotImplementedError: When the workstream or its dependencies
            are absent, so the caller can answer 501.
    """
    try:
        from agrigrade import model as module
    except ImportError as exc:  # pragma: no cover - exercised without the extra
        raise WorkstreamNotImplementedError(
            f"the model workstream is unavailable ({exc}); install the 'model' extra"
        ) from exc
    return module


def features_module() -> ModuleType:
    """Import ``agrigrade.features`` on demand.

    Raises:
        WorkstreamNotImplementedError: When the workstream or its dependencies
            are absent, so the caller can answer 501.
    """
    try:
        from agrigrade import features as module
    except ImportError as exc:
        raise WorkstreamNotImplementedError(
            f"the feature-extraction workstream is unavailable ({exc}); "
            f"install the 'features' extra"
        ) from exc
    return module


def workstream_status() -> dict[str, bool]:
    """Report which workstreams import in this process, for ``/health``.

    Import failures are reported as ``False`` rather than raised, because a
    health check that raises is not a health check.
    """
    status: dict[str, bool] = {}
    for name, loader in (("features", features_module), ("model", model_module)):
        try:
            loader()
        except WorkstreamNotImplementedError:
            status[name] = False
        else:
            status[name] = True
    return status


def load_model(artifact: str = DEFAULT_ARTIFACT, *, refresh: bool = False) -> LoadedModel:
    """Load and cache the grading model.

    Args:
        artifact: Artifact name, without the bundle suffix.
        refresh: Bypass the cache and read the artifact again.

    Returns:
        A :class:`LoadedModel`.

    Raises:
        WorkstreamNotImplementedError: The model workstream is not importable.
        ModelNotLoadedError: No artifact exists yet. The message names the
            training command rather than failing opaquely.
    """
    global _cached
    if _cached is not None and not refresh and artifact == DEFAULT_ARTIFACT:
        return _cached

    model_module()  # 501s if the workstream is absent
    # `agrigrade.model` only lazily re-exports a few names, so the artifacts
    # submodule is imported explicitly rather than reached through the package.
    from importlib import import_module

    try:
        artifacts = import_module("agrigrade.model.artifacts")
    except ImportError as exc:  # pragma: no cover - exercised without the extra
        raise WorkstreamNotImplementedError(
            f"the model workstream is unavailable ({exc}); install the 'model' extra"
        ) from exc
    path = Path(artifacts.default_path(artifact))
    if not path.exists():
        raise ModelNotLoadedError(
            f"no model artifact at {path}. Build one with "
            f"`python -m agrigrade.model.train`."
        )
    try:
        bundle = artifacts.load(path, verify=True)
    except Exception as exc:
        raise ModelNotLoadedError(f"could not load {path}: {exc}") from exc

    loaded = LoadedModel(
        grader=bundle.grader,
        manifest=bundle.manifest(),
        feature_names=tuple(bundle.feature_order),
        schema_version=int(bundle.schema_version),
    )
    if artifact == DEFAULT_ARTIFACT:
        with _lock:
            _cached = loaded
    return loaded


def clear_cache() -> None:
    """Drop the cached model. Used by tests that swap artifacts."""
    global _cached
    with _lock:
        _cached = None


__all__ = [
    "DEFAULT_ARTIFACT",
    "LoadedModel",
    "clear_cache",
    "features_module",
    "load_model",
    "model_module",
    "workstream_status",
]
